version: "3.9"

services:
  uvicorn:
    container_name: uvicorn
    image: yulianrudenko/fastapi_blog:latest
    command: 
      - /bin/sh
      - -c
      - |
        alembic upgrade head
        uvicorn --host 0.0.0.0 --port 80 --reload app.main:app
    env_file:
      - ./env/prod.env
    ports:
      - "80:80"
    restart: "no"
