version: "3.9"

services:
  db:
    container_name: db
    image: postgres:15.2-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: "no"


volumes:
  db:
    name: db_fastapi
