version: "3.9"

services:
  uvicorn:
    container_name: uvicorn
    build:
      context: ./web
      dockerfile: Dockerfile
    image: uvicorn
    command: uvicorn --host 0.0.0.0 --port 80 --reload app.main:app
    volumes:
      - ./web:/home/web/
    env_file:
      - .env
    ports:
      - "80:80"
    restart: "no"

  fastapi_db:
    container_name: fastapi_db
    image: postgres:15.2-alpine
    volumes:
      - fastapi_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: "no"


volumes:
  fastapi_db:
    name: fastapi_db
