version: "3.9"

services:
  uvicorn:
    container_name: uvicorn
    image: yulianrudenko/fastapi_blog:latest
    command: 
      - /bin/sh
      - -c
      - |
        alembic upgrade head
        uvicorn --host 0.0.0.0 --port 80 --reload app.main:app
    env_file:
      - ./env/prod.env
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  db:
    container_name: db
    image: postgres:15.2-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./env/prod.env
    ports:
      - "5432:5432"
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db:
    name: db
